import { IsNotEmpty, IsNumber, IsString } from 'class-validator';
import { Invoice } from '@getalby/lightning-tools';
import { ApiProperty } from '@nestjs/swagger';

export class MakePaymentDTO {
  @ApiProperty({
    example: '',
    description: "NWC Url generated by the customer's walle",
    name: 'NWCUrl',
  })
  @IsString()
  @IsNotEmpty()
  NWCUrl: string;

  @ApiProperty({
    example: 100,
    description: 'Amount to pay in sats',
    name: 'amount',
  })
  @IsNumber()
  amount: number;
}

export type MakePaymentResponse = {
  message: string;
  payment: Payment;
};

// the type that Alby SDK's pay method returns:
export type Payment = {
  invoice: Invoice;
  preimage: string;
  fees_paid: number;
};
